### ISSUE TITLE
Not working on Quest 2

### ISSUE THREAD

**Issue by WilsonBradley** [reloxx13/QuestAppLauncher_Assets#11]
Really wished I could get this working on Quest 2
Used to work on Quest 1 

Have not found ANY clear instructions.

Thanks

**Comment by reloxx13** [comment]
it work, as escribed in readme.

**Comment by WilsonBradley** [comment]
Any suggestions, besides factory reset, on how to trouble shoot any culprit conflicting app or cleanly / completely remove any left over data / then clean reinstall .
Everything I have done , for some reason Icons still don't show up. 
What I have done so far;
Cleared data/cache and uninstalled app.
Clean reinstall from SideQuest repository. 

Is there another place I should clean?
