### ISSUE TITLE
Game "Larcenauts" categorized in 2D

### ISSUE THREAD

**Issue by jamesst20** [reloxx13/QuestAppLauncher_Assets#19]
Hi,

I believe the game should be in the Quest tab along with the others :)

Thank you!

**Comment by jamesst20** [comment]
Thanks for the kind support!

**Comment by reloxx13** [comment]
U r wrong here and the qal dev is inactive

**Comment by jamesst20** [comment]
> U r wrong here and the qal dev is inactive

I see. Sorry for the troubles caused then :)
