### ISSUE TITLE
Custom Folder Creation

### ISSUE THREAD

**Issue by acidtaz** [reloxx13/QuestAppLauncher_Assets#20]
HI there,
I am wondering if there is a way to create the custom folders inside the app on a Quest 2 device?

It looks like from the Readme that the only way is to use the appnames.json file is that correct?  It would be nice if we could make the changes inside the program like the other launcher on SideQuest called the PI Launcher. 

Just want to make sure I'm not missing something. I thought it was supposed to show up with the Genres but none show up for me I tried changing their location and turning off the standard ones but no luck.  

Any help you could provide would me much appreciated.
If you can't do from the app does one of the utilities in here create a custom appnames.json file that I could then go update instead of having to create from scratch?

Kevin

**Comment by reloxx13** [comment]
wrong repo

**Comment by acidtaz** [comment]
I'm sorry but I'm kind of new to GitHub and not a programmer. 
I downloaded and installed the app from SideQuest, are you saying that there is another version that this is possible? 
Or what do you mean by wrong repo, and can you supply me a link with the correct repo?
Thank you very much once I figure this out I can update my sidequest review also.
