### ISSUE TITLE
VR Practical Shooting wrong app id

### ISSUE THREAD

**Issue by mrexodia** [reloxx13/QuestAppLauncher_Assets#21]
Hello, thanks for keeping up to date versions of the app names and icons! I found that you have the game `VR Practical Shooting` listed as `com.autogen.1637568944642`, but the actual id is `com.blobworks.VRPracticalShooting`. Is there a way to contribute the correct app id to this repository?

**Comment by reloxx13** [comment]
ill checl it later. the app ids are loaded from oculus graph api directly.

**Comment by reloxx13** [comment]
fixed in next release
